# Generated by Django 2.0.1 on 2018-04-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rf', '0003_auto_20180412_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='sample_id',
            new_name='sensor',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.AddField(
            model_name='signal',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rf.Device'),
        ),
    ]
