# Generated by Django 2.0.5 on 2018-05-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf', '0007_auto_20180507_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='ssid',
            field=models.CharField(max_length=100),
        ),
    ]
