# Generated by Django 2.0.5 on 2018-05-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rf', '0008_auto_20180507_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='pictureFileName',
        ),
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rf.ImageModel'),
        ),
    ]
