# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_id', models.IntegerField(default=0)),
                ('encryption_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulation_id', models.IntegerField(default=0)),
                ('modulation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antenna_type', models.IntegerField(default=0)),
                ('antenna_direction', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('elevation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulation', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('bssid', models.CharField(max_length=17)),
                ('encryption', models.IntegerField(default=0)),
                ('channel', models.IntegerField(default=0)),
                ('essid', models.CharField(max_length=255)),
            ],
        ),
    ]
